spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mobang
    username: mobang
    password: mobang
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl_auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true

server:
  port: 8000