spring:
  datasource:
    url: jdbc:mysql://db:3306/mobang?autoReconnection=true
    username: mobang
    password: mobang1234~!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl_auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

server:
  port: 8000